In [2]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [3]:
df = pd.read_csv("C:\\Users\\DELL\\OneDrive\\Desktop\\ML\\WORKBOOK\\Tweets.csv")
df

                 tweet_id  ...               user_timezone
0      570306133677760513  ...  Eastern Time (US & Canada)
1      570301130888122368  ...  Pacific Time (US & Canada)
2      570301083672813571  ...  Central Time (US & Canada)
3      570301031407624196  ...  Pacific Time (US & Canada)
4      570300817074462722  ...  Pacific Time (US & Canada)
...                   ...  ...                         ...
14635  569587686496825344  ...                         NaN
14636  569587371693355008  ...                         NaN
14637  569587242672398336  ...                         NaN
14638  569587188687634433  ...  Eastern Time (US & Canada)
14639  569587140490866689  ...                         NaN

[14640 rows x 15 columns]

In [4]:
# keeping only required columns

# df = df[["text","airline_sentiment"]]
# df

In [5]:
X = df.drop(columns="airline_sentiment")
y = df["airline_sentiment"]

In [6]:
xtrain, xtest, ytrain, ytest = train_test_split(X,y,train_size=0.8, random_state=42)

In [7]:
vectorizer = CountVectorizer(stop_words='english')
# stop_words='english' gives only important words
# OR we can mention our own stopwords and it will ignore them
# vertorizer = CountVectorizer(stop_words=['the','a','is'])

In [8]:
xtrain.shape

(11712, 14)

In [9]:
vectorizer.fit_transform(xtrain)
# <Compressed Sparse Row sparse matrix of dtype 'int64'
	# with 1 stored elements and shape (1, 1)>
values = vectorizer.fit_transform(xtrain['text'])
# <Compressed Sparse Row sparse matrix of dtype 'int64'
	# with 186804 stored elements and shape (11712, 13267)>

In [10]:
values = values.toarray()

In [11]:
cols = vectorizer.get_feature_names_out() #gives values acc to ASII values
cols

array(['00', '000', '000114', ..., 'zv2pt6trk9', 'zv6cfpohl5',
       'zvfmxnuelj'], shape=(12987,), dtype=object)

In [12]:
updated_xtrain = pd.DataFrame(data = values,columns=cols) #new dataframe with row values and column names
updated_xtrain

       00  000  000114  000ft  ...  zurich  zv2pt6trk9  zv6cfpohl5  zvfmxnuelj
0       0    0       0      0  ...       0           0           0           0
1       0    0       0      0  ...       0           0           0           0
2       0    0       0      0  ...       0           0           0           0
3       0    0       0      0  ...       0           0           0           0
4       0    0       0      0  ...       0           0           0           0
...    ..  ...     ...    ...  ...     ...         ...         ...         ...
11707   0    0       0      0  ...       0           0           0           0
11708   0    0       0      0  ...       0           0           0           0
11709   0    0       0      0  ...       0           0           0           0
11710   0    0       0      0  ...       0           0           0           0
11711   0    0       0      0  ...       0           0           0           0

[11712 rows x 12987 columns]

In [13]:
xtest.shape

(2928, 14)

In [14]:
vectorizer.transform(xtest)
# <Compressed Sparse Row sparse matrix of dtype 'int64'
	# with 2 stored elements and shape (14, 12987)>
updated_xtest = vectorizer.transform(xtest['text'])
# <Compressed Sparse Row sparse matrix of dtype 'int64'
	# with 25293 stored elements and shape (2928, 12987)>