In [329]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score

In [330]:
df = pd.read_csv('data.csv')
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [331]:
df = df.drop(['date', 'street', 'city', 'statezip', 'country'], axis=1)

In [332]:
X = df.drop(columns = 'price')
y = df['price']

In [333]:
num_cols=X.select_dtypes(include='number').columns #X coz we've to choose from features
obj_cols=X.select_dtypes(include='object').columns

In [334]:
X[obj_cols] = X[obj_cols].astype('category')

In [335]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

In [336]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0

In [337]:
# nominal_columns = [
#     "street",
#     "city",
#     "statezip",
#     "country"
# # ]

In [338]:
numeric_columns = X.columns

preprocessor = ColumnTransformer(
    transformers=[
        ("scaler", StandardScaler(), numeric_columns)
    ]
)
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", KNeighborsRegressor())
    ]
)

In [339]:
pipeline.fit(xtrain, ytrain)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated'],
      dtype='str'))])),
                ('model', KNeighborsRegressor())])

In [340]:
ypred_train = pipeline.predict(xtrain)
ypred_test = pipeline.predict(xtest)

In [341]:
# train_accuracy = accuracy_score(ytrain, ypred_train)
# test_accuracy = accuracy_score(ytest, ypred_test)

# print("Training Accuracy :", train_accuracy)
# print("Testing Accuracy  :", test_accuracy)

In [342]:
# #n_neighbors=sqrt(n), metric='encoder'|'manhattan'
# model = KNeighborsRegressor(metric='euclidean',n_neighbors=3)
# #for KNN scaling preprocessing technique is required
# scaler = StandardScaler()
# # scaler.fit(X[num_cols])
# # X[num_cols] = scaler.transform(X[num_cols])

In [343]:
# model.fit(xtrain,ytrain)

In [ ]:
# #Model Evaluation
# train_accuracy = model.score(xtrain,ytrain)
# train_accuracy

0.6725312896626681

In [ ]:
# test_accuracy =model.score(xtest,ytest)
# test_accuracy

0.015276200126122186

In [ ]:
# print(f"Training Accuracy : {train_accuracy:.4f}")
# print(f"Testing Accuracy  : {test_accuracy:.4f}")

# if train_accuracy > 0.98 and test_accuracy < train_accuracy - 0.10:
#     print("Model is Overfitting")

# elif abs(train_accuracy - test_accuracy) <= 0.05:
#     print("Model is Good Fit")

# else:
#     print("Model is Underfitting")

Training Accuracy : 0.6725
Testing Accuracy  : 0.0153
Model is Underfitting

In [347]:
#sales dataset from kaggle