In [1]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('loan_data.csv')
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [3]:
X = df.drop(columns = 'loan_status')
y= df.loan_status

In [4]:
xtrain, xtest, ytrain, ytest = train_test_split(X,y,train_size=0.8, random_state=42)

In [5]:
#num_cols = X.select_dtypes(include='number').columns
obj_cols = X.select_dtypes(include='object').columns

C:\Users\DELL\AppData\Local\Temp\ipykernel_5780\1433802163.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = X.select_dtypes(include='object').columns

In [6]:
X[obj_cols].nunique()

person_gender                     2
person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [7]:
# person_gender                     2
# person_education                  5
# person_home_ownership             4
# loan_intent                       6
# previous_loan_defaults_on_file    2
# 2 unique values and less feature values do OneHotEncoding and more unique values do OrdinalEncoding

In [8]:
X['person_education'].unique()

<ArrowStringArray>
['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']
Length: 5, dtype: str

In [9]:
order = ['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']

In [10]:
obj_cols.drop(['person_education'])

Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='str')

In [11]:
# preprocessing = ColumnTransformer(
#     transformers=[
#         ('onehot_encoder', OneHotEncoder(handle_unknown='ignore'),obj_cols.drop('person_education')),
#         ('ordinal_encoder', OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1),['person_education']))
#     ],remainder='passthrough'
# )

# main_pipeline = Pipeline(
#     steps=[
#         ('preprocessing', preprocessing),
#         ('model', DecisionTreeClassifier(random_state=42))
#     ]
# )

# grid_search_cv = GridSearchCV(
#     estimator = main_pipeline,
#     param_grid = {
#         'model__criterion':['gini','entropy'], #model__ is used to access the parameters of the model in the pipeline i.e go inside model and access the parameters of DecisionTreeClassifier
#         'model__max_depth':[None,5,10,50,100], #if we use algorithm no need to use model__ but if we use pipeline then we need to use model__ to access the parameters of the model in the pipeline
#         'model__min_samples_split':[2,5,7,10],
#         'model__min_samples_leaf':[1,3,5,7,10],
#         'model__splitter':['best', 'random']
#     },
# verbose=1)
# grid_search_cv.fit(xtrain,ytrain)

In [12]:
# preprocessing = ColumnTransformer(
#     transformers=[
#         ('onehot_encoder', OneHotEncoder(handle_unknown='ignore'), obj_cols.drop('person_education')),
#         ('ordinal_encoder', OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1), ['person_education'])
#     ],
#     remainder='passthrough'
# )

# main_pipeline = Pipeline(
#     steps=[
#         ('preprocessing', preprocessing),
#         ('model', DecisionTreeClassifier(random_state=42))
#     ]
# )

# grid_search_cv = GridSearchCV(
#     estimator = main_pipeline,
#     param_grid = {
#         'model__criterion':['gini','entropy'],
#         'model__max_depth':[None,5,10,50,100],
#         'model__min_samples_split':[2,5,7,10],
#         'model__min_samples_leaf':[1,3,5,7,10],
#         'model__splitter':['best', 'random']
#     },
#     verbose=1,n_jobs=-1
# )
# grid_search_cv.fit(xtrain,ytrain)

In [ ]:
preprocessing = ColumnTransformer(
    transformers=[
        ('onehot_encoder', OneHotEncoder(handle_unknown='ignore'), obj_cols.drop('person_education')),
        ('ordinal_encoder', OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1), ['person_education'])
    ],
    remainder='passthrough'
)

main_pipeline = Pipeline(
    steps=[
        ('preprocessing', preprocessing),
        ('model', SVC(random_state=42))
    ]
)

grid_search_cv = GridSearchCV(
    estimator = main_pipeline,
    param_grid = {
        'model__C':[0.01,0.1,1.0,10,100],
        'model__kernel':['linear', 'poly', 'rbf', 'sigmoid']
    },
    verbose=1,n_jobs=-1
)
grid_search_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

In [ ]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='str')),
                                                 ('ordinal_encoder',
                                                  OrdinalEncoder(categories=[['Master',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Associate',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 DecisionTreeClassifier(criterion='entropy', max_depth=10,
                                        random_state=42))])

In [ ]:
grid_search_cv.best_params_

{'model__criterion': 'entropy',
 'model__max_depth': 10,
 'model__min_samples_leaf': 1,
 'model__min_samples_split': 2,
 'model__splitter': 'best'}

In [ ]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.54374146, 0.409128  , 0.61099949, 0.41524334, 0.60886197,
        0.37530193, 0.57531104, 0.42309184, 0.56812048, 0.39872737,
        0.58563905, 0.4413805 , 0.57774992, 0.37070189, 0.61188817,
        0.38660522, 0.58796735, 0.44817767, 0.60301881, 0.34639721,
        0.58523035, 0.41366477, 0.57727513, 0.40404773, 0.58277321,
        0.34120073, 0.56238523, 0.39315248, 0.58403449, 0.36240091,
        0.56451273, 0.34377179, 0.56037526, 0.35694542, 0.55732369,
        0.34402924, 0.53643465, 0.37387118, 0.57559781, 0.42108107,
        0.44291949, 0.39717011, 0.46867933, 0.3680922 , 0.43731089,
        0.40598702, 0.46529455, 0.41918864, 0.44871373, 0.38598576,
        0.45986738, 0.4146534 , 0.4955667 , 0.43688893, 0.43908453,
        0.39047408, 0.46885509, 0.39908624, 0.47677097, 0.39054608,
        0.469807  , 0.4341321 , 0.47611213, 0.40271573, 0.46144843,
        0.37644272, 0.4766161 , 0.38656268, 0.44496512, 0.39716744,
        0.46992064, 0.37804155, 0.46153836, 0.38926597, 0.46393518,
        0.39024053, 0.43901849, 0.37080216, 0.49685302, 0.40749025,
        0.52042027, 0.39084678, 0.5198215 , 0.36156583, 0.51941686,
        0.35954952, 0.51413121, 0.37778139, 0.52632036, 0.36916289,
        0.51100974, 0.36693802, 0.51872382, 0.34069743, 0.50727777,
        0.41042261, 0.52891994, 0.37832737, 0.50120082, 0.37001491,
        0.50286255, 0.42825089, 0.51111441, 0.37617092, 0.52071166,
        0.3928134 , 0.53332682, 0.3762424 , 0.53083711, 0.41875229,
        0.53324037, 0.46570668, 0.52264085, 0.39871583, 0.51784263,
        0.36982946, 0.51555138, 0.36072006, 0.47479467, 0.43240557,
        0.62962813, 0.35725207, 0.59022317, 0.36309257, 0.58291049,
        0.38034682, 0.63932233, 0.4056819 , 0.54782147, 0.37306719,
        0.56158719, 0.37371755, 0.58043671, 0.36423383, 0.53953342,
        0.36318469, 0.56111774, 0.36077843, 0.56923304, 0.38051505,
        0.56884947, 0.36115446, 0.58987451, 0.41104074, 0.57599139,
        0.35852518, 0.56762662, 0.35988884, 0.57664876, 0.37482791,
        0.67595735, 0.43341393, 0.58198295, 0.39230294, 0.54630723,
        0.34859414, 0.5832572 , 0.37821097, 0.51779594, 0.35578842,
        0.62348785, 0.41147251, 0.5966043 , 0.41709976, 0.61621075,
        0.39723706, 0.59845047, 0.35664144, 0.61824102, 0.43234997,
        0.5476171 , 0.35804157, 0.58709803, 0.41830506, 0.57928948,
        0.36720243, 0.57799449, 0.36604729, 0.58229041, 0.37032328,
        0.58225245, 0.35473371, 0.54879947, 0.40512767, 0.59415898,
        0.38443098, 0.56900058, 0.38528814, 0.58337574, 0.40850916,
        0.57335968, 0.37380614, 0.5674706 , 0.37590113, 0.57285581,
        0.40112453, 0.55853705, 0.39238377, 0.57917233, 0.40026073,
        0.66499352, 0.38094821, 0.67467775, 0.37944927, 0.64148421,
        0.37158155, 0.63990703, 0.38787479, 0.66333599, 0.3563087 ,
        0.63905921, 0.36124983, 0.65264769, 0.35840449, 0.64168029,
        0.364189  , 0.6769187 , 0.35917249, 0.63152924, 0.38080144,
        0.63078175, 0.36783123, 0.65122366, 0.37320962, 0.62994275,
        0.34839501, 0.73685222, 0.3893126 , 0.63709831, 0.37027245,
        0.63294282, 0.37552462, 0.60859847, 0.34270124, 0.62695842,
        0.37067676, 0.65466914, 0.36328359, 0.61209955, 0.35381169,
        0.48545966, 0.36865993, 0.47253408, 0.4085227 , 0.49961104,
        0.34647303, 0.48035159, 0.3785625 , 0.51246505, 0.38946385,
        0.50193338, 0.42188582, 0.47985458, 0.36891818, 0.49766598,
        0.4148222 , 0.48547482, 0.40809312, 0.48073573, 0.39039855,
        0.49031038, 0.4250608 , 0.47097931, 0.37413554, 0.50245914,
        0.36862669, 0.50140042, 0.38625498, 0.49835978, 0.42454119,
        0.50899463, 0.3937448 , 0.47411356, 0.39593434, 0.47145066,
        0.38078504, 0.48922853, 0.38870988, 0.48202119, 0.41535416,
        0.56608663, 0.41338382, 0.56287656, 0.36839447, 0.57915244,
        0.37042718, 0.54525919, 0.33529849, 0.53238478, 0.38431525,
        0.55438037, 0.35467405, 0.56151929, 0.43465877, 0.56278663,
        0.36750484, 0.56178308, 0.40684924, 0.55757942, 0.38229828,
        0.56366615, 0.35842071, 0.5583046 , 0.37362413, 0.58501301,
        0.41044002, 0.56728606, 0.40026884, 0.54464655, 0.39677591,
        0.55076971, 0.37041998, 0.49455538, 0.38520575, 0.56542954,
        0.37253494, 0.59710078, 0.40336413, 0.57623158, 0.42814946,
        0.68707571, 0.43241882, 0.66919422, 0.38609467, 0.66242743,
        0.39424715, 0.64309049, 0.40123835, 0.6705503 , 0.40258217,
        0.67055173, 0.38406358, 0.6845067 , 0.3950563 , 0.6703342 ,
        0.39294276, 0.65051093, 0.35798874, 0.64216161, 0.38148627,
        0.65546188, 0.38288527, 0.66290236, 0.399191  , 0.66146832,
        0.34729471, 0.62004166, 0.38871498, 0.57856636, 0.34285512,
        0.65294871, 0.40984173, 0.61510358, 0.3858253 , 0.62118855,
        0.4046864 , 0.61775522, 0.39170923, 0.61244841, 0.34711719,
        0.6411284 , 0.41245284, 0.67663703, 0.37146764, 0.63609409,
        0.37661724, 0.71213021, 0.41244693, 0.62947965, 0.40847821,
        0.66405168, 0.37456713, 0.69627819, 0.36701574, 0.65818472,
        0.37062182, 0.68406563, 0.39875097, 0.66481557, 0.38447075,
        0.65324116, 0.42924995, 0.63939037, 0.39349031, 0.60886974,
        0.37368884, 0.66136923, 0.3716588 , 0.62160001, 0.3540843 ,
        0.62344866, 0.36006494, 0.60936918, 0.37013321, 0.59588094,
        0.34964609, 0.61339269, 0.38740211, 0.62281852, 0.34203176]),
 'std_fit_time': array([0.01784141, 0.03792442, 0.02424873, 0.03610465, 0.01114297,
        0.0346482 , 0.07349336, 0.04906556, 0.03810812, 0.03641346,
        0.05438869, 0.03501881, 0.0194351 , 0.03707421, 0.07011716,
        0.0364311 , 0.03749577, 0.10660189, 0.05764406, 0.03541961,
        0.06733931, 0.04704817, 0.08349747, 0.02547471, 0.01190352,
        0.02296842, 0.04109635, 0.03289132, 0.06985654, 0.04526444,
        0.01547592, 0.02209969, 0.0292344 , 0.02223277, 0.01832549,
        0.02056414, 0.03620136, 0.03388376, 0.0804107 , 0.04887956,
        0.06950204, 0.04234856, 0.04421841, 0.02868909, 0.03024013,
        0.01856313, 0.05332188, 0.03337928, 0.00901016, 0.01823966,
        0.03469768, 0.04869483, 0.04848177, 0.0343595 , 0.03974333,
        0.01265076, 0.04270587, 0.03479592, 0.03051872, 0.01937333,
        0.05888023, 0.05811001, 0.07456873, 0.06822616, 0.02512933,
        0.01051837, 0.02672828, 0.01557281, 0.01890273, 0.01742216,
        0.02895072, 0.00257297, 0.01580345, 0.02013834, 0.01561981,
        0.00451501, 0.02290008, 0.02716538, 0.07359313, 0.06003329,
        0.04396484, 0.04182028, 0.01578006, 0.01953702, 0.02400306,
        0.01834932, 0.02829158, 0.0284477 , 0.0375826 , 0.01602621,
        0.01907452, 0.0108171 , 0.03511312, 0.02878298, 0.04475252,
        0.07081802, 0.03254386, 0.02368902, 0.05099205, 0.02136827,
        0.04584351, 0.04706931, 0.01926516, 0.03114445, 0.07059678,
        0.04225352, 0.03091205, 0.01828029, 0.06828314, 0.07423229,
        0.04214239, 0.02687806, 0.07252961, 0.05164934, 0.02182773,
        0.01407848, 0.03653447, 0.0172671 , 0.03260438, 0.04228315,
        0.02725763, 0.05101134, 0.01680638, 0.04312352, 0.02146276,
        0.04582269, 0.10715368, 0.06909558, 0.04521332, 0.03584197,
        0.03820591, 0.02369192, 0.04959242, 0.05162241, 0.01622207,
        0.02570557, 0.02517378, 0.02799987, 0.02507904, 0.02708173,
        0.03089306, 0.02846497, 0.07456983, 0.03215001, 0.02581425,
        0.03067243, 0.02503786, 0.04610103, 0.04657956, 0.02989928,
        0.03934968, 0.03203222, 0.0959034 , 0.04461329, 0.03216295,
        0.02962232, 0.08921672, 0.0414706 , 0.03651834, 0.02416058,
        0.05907795, 0.03971942, 0.02649757, 0.06745232, 0.01879839,
        0.04088254, 0.02625903, 0.02133603, 0.09924686, 0.09243617,
        0.03089416, 0.02101335, 0.06319153, 0.04695756, 0.04018623,
        0.02777649, 0.02376859, 0.03501757, 0.02310911, 0.03740283,
        0.02080889, 0.02739001, 0.02871023, 0.06577026, 0.05994014,
        0.05260208, 0.00762926, 0.04278629, 0.0828384 , 0.06123324,
        0.03300061, 0.03124789, 0.02842745, 0.01893893, 0.04415632,
        0.04452258, 0.0180727 , 0.02615244, 0.08674849, 0.07101117,
        0.02176874, 0.03088242, 0.02305644, 0.0650048 , 0.03625839,
        0.03891797, 0.02254075, 0.05588708, 0.05761656, 0.03507144,
        0.01489993, 0.05253584, 0.02025166, 0.04342976, 0.0194659 ,
        0.04849084, 0.03071772, 0.04979851, 0.08865838, 0.03179444,
        0.0303118 , 0.05716993, 0.05555508, 0.05089097, 0.05698172,
        0.04267824, 0.08802816, 0.03981069, 0.03261653, 0.0686598 ,
        0.01225141, 0.04934319, 0.04271935, 0.02633683, 0.03253683,
        0.05830919, 0.07617136, 0.03625202, 0.0208106 , 0.0461157 ,
        0.02846558, 0.00819481, 0.04250343, 0.03186438, 0.01859964,
        0.01360813, 0.01643067, 0.00779444, 0.07076078, 0.04145732,
        0.07556263, 0.04367693, 0.02856274, 0.02235222, 0.07091994,
        0.07077513, 0.07113159, 0.05244648, 0.05811904, 0.02533258,
        0.06387913, 0.07206443, 0.02637377, 0.01285096, 0.03473371,
        0.01289798, 0.06347907, 0.06789844, 0.04637405, 0.07487163,
        0.0906169 , 0.03221508, 0.05295089, 0.0424792 , 0.01727435,
        0.03318915, 0.03155892, 0.01334137, 0.03076326, 0.05230182,
        0.0758644 , 0.05731275, 0.03175818, 0.00998897, 0.0589976 ,
        0.05303714, 0.03343243, 0.02581073, 0.01648226, 0.04132101,
        0.01286908, 0.02505923, 0.05870009, 0.06400175, 0.03181051,
        0.01657648, 0.04734758, 0.03420451, 0.0226631 , 0.0344925 ,
        0.03501835, 0.02817118, 0.0255719 , 0.01740996, 0.06922342,
        0.05114624, 0.04685359, 0.04881758, 0.07260577, 0.02265837,
        0.06776544, 0.06006842, 0.02422131, 0.03137223, 0.02224594,
        0.02300224, 0.09886707, 0.07495782, 0.04646399, 0.02526789,
        0.09345756, 0.05146481, 0.02726414, 0.05490215, 0.0138867 ,
        0.067241  , 0.04625142, 0.03042226, 0.09293116, 0.04908455,
        0.02873419, 0.0485178 , 0.02397357, 0.0678583 , 0.02867486,
        0.06421501, 0.04414199, 0.04210868, 0.01636786, 0.05513625,
        0.02910814, 0.03601872, 0.02657092, 0.061282  , 0.03398278,
        0.03747306, 0.06781247, 0.04765216, 0.01238282, 0.02874727,
        0.06948833, 0.09471471, 0.02037425, 0.02564066, 0.06261456,
        0.03417564, 0.06490341, 0.03066853, 0.03938627, 0.03929499,
        0.06435825, 0.0286551 , 0.01974704, 0.07009482, 0.02100605,
        0.02195994, 0.07936543, 0.06145986, 0.06318783, 0.02231619,
        0.02701792, 0.05960195, 0.10473625, 0.05338594, 0.04208706,
        0.04090073, 0.05473503, 0.04109163, 0.01754162, 0.08702566,
        0.09997456, 0.06566593, 0.0795889 , 0.05869906, 0.02606824,
        0.04072938, 0.04876891, 0.03737099, 0.01993535, 0.03645844,
        0.04750611, 0.03350922, 0.03394218, 0.0449436 , 0.01318169,
        0.01954283, 0.05626128, 0.01776752, 0.06455601, 0.0681059 ]),
 'mean_score_time': array([0.05349674, 0.06918178, 0.05395737, 0.07598238, 0.05252056,
        0.05918894, 0.05515747, 0.07014189, 0.0597971 , 0.08179274,
        0.05993381, 0.07820306, 0.05704556, 0.07206793, 0.06011848,
        0.06722183, 0.06241875, 0.07252555, 0.05510883, 0.06264048,
        0.05688729, 0.0655828 , 0.06431875, 0.06528316, 0.06266675,
        0.06183434, 0.0656343 , 0.07048807, 0.06180387, 0.05365677,
        0.05843277, 0.09635897, 0.07776427, 0.09712849, 0.10600529,
        0.08519449, 0.07777605, 0.06732426, 0.05346513, 0.0663969 ,
        0.07334423, 0.0672956 , 0.07252054, 0.07193594, 0.06750174,
        0.07746716, 0.06801152, 0.06949716, 0.07916884, 0.0729156 ,
        0.07488375, 0.06773248, 0.06681662, 0.06595283, 0.06932817,
        0.0723084 , 0.06647148, 0.06423125, 0.07357802, 0.07415791,
        0.0668067 , 0.08121843, 0.07980957, 0.07627268, 0.06577873,
        0.07921524, 0.06965871, 0.07436147, 0.07570376, 0.07688088,
        0.07565446, 0.07812738, 0.08099041, 0.07100039, 0.07102289,
        0.07226739, 0.07348919, 0.06480188, 0.06670246, 0.07072372,
        0.06437545, 0.07095838, 0.06626105, 0.0722322 , 0.06719265,
        0.07101746, 0.06496091, 0.0703866 , 0.06579537, 0.07988386,
        0.07483983, 0.067242  , 0.05974498, 0.06609845, 0.06633677,
        0.07163377, 0.06382656, 0.06864309, 0.06214747, 0.06989851,
        0.05749688, 0.07078781, 0.06168475, 0.07237277, 0.06752229,
        0.06763573, 0.0634438 , 0.07557111, 0.06669183, 0.08527136,
        0.07285166, 0.07402124, 0.05892391, 0.08591552, 0.0639585 ,
        0.07406616, 0.07587295, 0.06999626, 0.06500707, 0.06954694,
        0.06295128, 0.06842165, 0.06097751, 0.07351999, 0.06912079,
        0.06434016, 0.06389146, 0.08028975, 0.06450396, 0.06343718,
        0.0556047 , 0.06202226, 0.04956832, 0.06174426, 0.06011653,
        0.06471448, 0.058814  , 0.06760015, 0.0598237 , 0.07477365,
        0.05876589, 0.06473069, 0.06355934, 0.06724429, 0.05664515,
        0.07154946, 0.05811548, 0.06721311, 0.0658308 , 0.06652107,
        0.06633968, 0.07340636, 0.0631876 , 0.07142868, 0.06054316,
        0.0715703 , 0.06654582, 0.06526508, 0.05714154, 0.06401572,
        0.06488128, 0.06693025, 0.06430635, 0.07110896, 0.06026759,
        0.07100396, 0.06129427, 0.06317792, 0.06057734, 0.0588933 ,
        0.06629643, 0.06405888, 0.0604497 , 0.07275271, 0.06228366,
        0.07051482, 0.06219125, 0.06330776, 0.05363655, 0.06516585,
        0.05495963, 0.07429328, 0.05568457, 0.07547221, 0.0681242 ,
        0.07421885, 0.06327181, 0.07365623, 0.05473986, 0.06947589,
        0.07019763, 0.06663175, 0.06064138, 0.07143846, 0.05928431,
        0.07156844, 0.06527724, 0.08409581, 0.0590817 , 0.06415687,
        0.06489935, 0.06300855, 0.06486001, 0.05308557, 0.06270003,
        0.06737633, 0.0643609 , 0.0639771 , 0.07105498, 0.06493874,
        0.0600945 , 0.06044359, 0.05644317, 0.06210108, 0.06659842,
        0.06875014, 0.05999265, 0.07057195, 0.05646529, 0.07856174,
        0.05645289, 0.05999136, 0.05462828, 0.06417356, 0.05657277,
        0.05918751, 0.07442794, 0.06300702, 0.06312609, 0.06903534,
        0.05957899, 0.06691265, 0.06180763, 0.06206584, 0.06272907,
        0.06026502, 0.06082149, 0.06520214, 0.05710135, 0.07018661,
        0.07937684, 0.07473898, 0.07171607, 0.08417668, 0.07445135,
        0.07836366, 0.08024192, 0.06658416, 0.07116437, 0.07706447,
        0.06915016, 0.06977038, 0.07206259, 0.07018714, 0.08200507,
        0.07049832, 0.088802  , 0.0794817 , 0.0651855 , 0.06956263,
        0.06899414, 0.06929107, 0.07875886, 0.06876793, 0.07578478,
        0.0725276 , 0.0775969 , 0.07214103, 0.07688837, 0.08387113,
        0.07284946, 0.07263288, 0.0640595 , 0.07275043, 0.07255473,
        0.0806077 , 0.08172698, 0.07270708, 0.06893735, 0.07131386,
        0.06564698, 0.08023486, 0.07459574, 0.07002726, 0.07345338,
        0.07162971, 0.057375  , 0.07141819, 0.0656117 , 0.07227521,
        0.06361914, 0.07657938, 0.05696988, 0.08543391, 0.06339846,
        0.07366028, 0.0620862 , 0.07782836, 0.06724114, 0.07012086,
        0.0616509 , 0.07312236, 0.06965184, 0.07891393, 0.07299676,
        0.08718376, 0.07276988, 0.07336154, 0.06190524, 0.06693325,
        0.05549812, 0.06179852, 0.07248821, 0.07268734, 0.06256428,
        0.07207947, 0.06420131, 0.07712426, 0.06841674, 0.081986  ,
        0.06455822, 0.07373114, 0.06618819, 0.07301459, 0.06276517,
        0.07147789, 0.06793585, 0.05810218, 0.05896721, 0.07519484,
        0.06675138, 0.06324725, 0.06900091, 0.06294141, 0.06762424,
        0.06817098, 0.06044602, 0.07308645, 0.06144891, 0.07653069,
        0.06220713, 0.07006292, 0.07174377, 0.06352072, 0.06667271,
        0.0647253 , 0.05224409, 0.06673813, 0.06550293, 0.06382999,
        0.09165397, 0.05027199, 0.06047683, 0.07083178, 0.06980162,
        0.07254529, 0.05769854, 0.07204237, 0.06847377, 0.07695312,
        0.06742482, 0.06925349, 0.05759764, 0.06025372, 0.06522322,
        0.07489724, 0.06131144, 0.07543645, 0.05997176, 0.06029725,
        0.06078768, 0.064189  , 0.0850749 , 0.06550422, 0.06494899,
        0.05846829, 0.06881332, 0.07507753, 0.06254268, 0.0573669 ,
        0.05958905, 0.08464317, 0.05794377, 0.07327924, 0.05761433,
        0.07110639, 0.06850805, 0.06477699, 0.06092505, 0.07000303,
        0.06619   , 0.07199707, 0.06114011, 0.07206855, 0.06362076,
        0.07217178, 0.06105852, 0.07716622, 0.05294156, 0.04512572]),
 'std_score_time': array([0.0085158 , 0.01754105, 0.01133356, 0.01174767, 0.00780864,
        0.00366884, 0.00898551, 0.00888348, 0.01632409, 0.02242135,
        0.0132522 , 0.01339263, 0.00792857, 0.02971605, 0.00956926,
        0.01094498, 0.01846948, 0.01795358, 0.01331689, 0.00934852,
        0.01008642, 0.01413982, 0.01427812, 0.00484033, 0.00945865,
        0.00478946, 0.00931371, 0.01532729, 0.00803894, 0.00815996,
        0.00935167, 0.06821802, 0.04701508, 0.06172614, 0.0399541 ,
        0.04983036, 0.01913581, 0.0069489 , 0.0074145 , 0.00891519,
        0.01897488, 0.00751161, 0.01487021, 0.01028774, 0.01594042,
        0.00932961, 0.00854984, 0.01013514, 0.01008128, 0.00586105,
        0.02367376, 0.01762   , 0.01393036, 0.00678657, 0.02006365,
        0.0066717 , 0.00764242, 0.00701144, 0.00878858, 0.01257929,
        0.01007144, 0.0085806 , 0.01938161, 0.01582311, 0.00931859,
        0.01245855, 0.00550805, 0.00725773, 0.01225955, 0.00566369,
        0.00409943, 0.00464086, 0.0064889 , 0.00693446, 0.00126102,
        0.00625698, 0.0148957 , 0.00599388, 0.01310292, 0.01125858,
        0.01774772, 0.00817206, 0.01263999, 0.01119914, 0.01341133,
        0.01112818, 0.00636869, 0.00757918, 0.01084817, 0.01500485,
        0.00680196, 0.00659338, 0.00966769, 0.00456604, 0.01259179,
        0.01806387, 0.01207055, 0.00502497, 0.00925054, 0.01132692,
        0.00679049, 0.00564839, 0.00339117, 0.00995252, 0.01670386,
        0.01361879, 0.01055405, 0.00413888, 0.01941791, 0.02242774,
        0.01675534, 0.00877141, 0.00946293, 0.02119378, 0.00535551,
        0.01563088, 0.01934346, 0.0088335 , 0.01057949, 0.01023515,
        0.01465129, 0.00960865, 0.01279492, 0.01253364, 0.01374791,
        0.00848711, 0.01441945, 0.02686224, 0.01647583, 0.00844274,
        0.01305949, 0.0038333 , 0.00661224, 0.00889973, 0.01224329,
        0.00477857, 0.01063489, 0.00721033, 0.00895808, 0.0095507 ,
        0.0120279 , 0.00393848, 0.01521236, 0.00412673, 0.00945749,
        0.00685807, 0.01141623, 0.01067953, 0.01720236, 0.01084589,
        0.01113333, 0.00867244, 0.01951775, 0.00706312, 0.01358981,
        0.01684384, 0.01135088, 0.01060534, 0.00875424, 0.00225471,
        0.0111328 , 0.01106688, 0.01107095, 0.01570189, 0.01183556,
        0.01236441, 0.0117914 , 0.00675021, 0.01158022, 0.00821921,
        0.01162283, 0.00768419, 0.00758861, 0.01309413, 0.01081699,
        0.00710952, 0.00998861, 0.0064891 , 0.00482653, 0.01101677,
        0.00962767, 0.0146312 , 0.0036808 , 0.01556011, 0.01119213,
        0.01420348, 0.00924094, 0.01840595, 0.00529494, 0.01575589,
        0.01131281, 0.01033508, 0.00888282, 0.01724372, 0.01095317,
        0.00914237, 0.01249576, 0.02188382, 0.01072312, 0.00983545,
        0.01300216, 0.01741836, 0.01167483, 0.00566783, 0.01316971,
        0.01327596, 0.01316089, 0.0102281 , 0.01002081, 0.01220645,
        0.01066125, 0.00864753, 0.00638849, 0.00798585, 0.01512416,
        0.01585185, 0.01228694, 0.01045158, 0.0128647 , 0.00983655,
        0.00744092, 0.01109437, 0.00306505, 0.01391529, 0.01174565,
        0.00270278, 0.02389906, 0.01547057, 0.01357304, 0.02317356,
        0.00758422, 0.01198324, 0.01319435, 0.00829421, 0.01072654,
        0.00837358, 0.00590186, 0.01698138, 0.00827575, 0.01030382,
        0.00731874, 0.00650353, 0.01088315, 0.00841467, 0.01144655,
        0.02119913, 0.01374276, 0.00298422, 0.01653661, 0.01131908,
        0.01255651, 0.00881529, 0.00844585, 0.00578888, 0.02799081,
        0.00652871, 0.03809697, 0.01566663, 0.00629454, 0.00683408,
        0.0148604 , 0.0017983 , 0.01223632, 0.00417613, 0.01270321,

In [ ]:
results = pd.DataFrame(grid_search_cv.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.543741,0.017841,0.053497,0.008516,gini,None,1,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.896806,0.900972,0.899444,0.901250,0.895694,0.898833,0.002225,316
1,0.409128,0.037924,0.069182,0.017541,gini,None,1,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.888333,0.891111,0.884583,0.892639,0.889722,0.889278,0.002749,355
2,0.610999,0.024249,0.053957,0.011334,gini,None,1,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.895139,0.901806,0.900000,0.901667,0.901250,0.899972,0.002499,301
3,0.415243,0.036105,0.075982,0.011748,gini,None,1,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.895278,0.897778,0.890000,0.889306,0.895417,0.893556,0.003315,349
4,0.608862,0.011143,0.052521,0.007809,gini,None,1,7,best,"{'model__criterion': 'gini', 'model__max_depth...",0.897917,0.900556,0.900556,0.903472,0.901667,0.900833,0.001807,292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.349646,0.019543,0.072172,0.006490,entropy,100,10,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.902222,0.909444,0.899861,0.904583,0.909722,0.905167,0.003904,186
396,0.613393,0.056261,0.061059,0.008761,entropy,100,10,7,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908194,0.915139,0.912778,0.912917,0.912639,0.912333,0.002264,81
397,0.387402,0.017768,0.077166,0.018856,entropy,100,10,7,random,"{'model__criterion': 'entropy', 'model__max_de...",0.902222,0.909444,0.899861,0.904583,0.909722,0.905167,0.003904,186
398,0.622819,0.064556,0.052942,0.008182,entropy,100,10,10,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908194,0.915139,0.912778,0.912917,0.912639,0.912333,0.002264,81
399,0.342032,0.068106,0.045126,0.010905,entropy,100,10,10,random,"{'model__criterion': 'entropy', 'model__max_de...",0.902222,0.909444,0.899861,0.904583,0.909722,0.905167,0.003904,186

In [ ]:
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
302,0.558305,0.025572,0.069652,0.011940,entropy,10,5,10,best,"{'model__criterion': 'entropy', 'model__max_de...",0.918472,0.927361,0.914444,0.921250,0.920417,0.920389,0.004204,1
300,0.563666,0.035018,0.061651,0.007456,entropy,10,5,7,best,"{'model__criterion': 'entropy', 'model__max_de...",0.918472,0.927361,0.914444,0.921250,0.920417,0.920389,0.004204,1
298,0.557579,0.022663,0.067241,0.014887,entropy,10,5,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.918472,0.927361,0.914444,0.921250,0.920417,0.920389,0.004204,1
280,0.566087,0.075864,0.065647,0.015842,entropy,10,1,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.919583,0.926111,0.914861,0.920833,0.920556,0.920389,0.003583,1
296,0.561783,0.047348,0.062086,0.009667,entropy,10,5,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.918472,0.927361,0.914444,0.921250,0.920417,0.920389,0.004204,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.378042,0.002573,0.078127,0.004641,gini,5,7,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872639,0.872417,0.000461,393
77,0.370802,0.027165,0.064802,0.005994,gini,5,10,7,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
79,0.407490,0.060033,0.070724,0.011259,gini,5,10,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
73,0.389266,0.020138,0.071000,0.006934,gini,5,10,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
75,0.390241,0.004515,0.072267,0.006257,gini,5,10,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397

In [ ]:
#do the same with logistic regression and random forest